language: ruby
rvm:
 - 2.3.1

install:
  - bundle install
  - npm install

script:
  - bundle exec rspec
  - npm test

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

test:
  adapter: postgresql
  database: travis_ci_test
